### ISSUE TITLE
設定ファイルの記述方法（v2）「複数の宛先に送信する場合」の説明について

### ISSUE THREAD

**Issue by miralkashiwagi** [dounokouno/TransmitMail#96]
[設定ファイルの記述方法（v2）](https://github.com/dounokouno/TransmitMail/wiki/%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E8%A8%98%E8%BF%B0%E6%96%B9%E6%B3%95%EF%BC%88v2%EF%BC%89) に関しまして

> 複数の宛先に送信する場合、 `email: info@example.com,test@example.com` と記述します。
> 複数の宛先を設定する場合は、 `auto_reply_from_email` と場合によっては `return_path` に、 1 つの、 `auto_reply_from_email` と `return_path` で同じメールアドレスを設定してください。

とありますが、`auto_reply_from_email` への設定では動作しないようです。

`from_email` と `return_path` に設定した場合は正しく複数の送信先に送信できました。

**Comment by dounokouno** [comment]
@miralkashiwagi 様

Wiki ページのご指摘ありがとうございます。

> `auto_reply_from_email` への設定では動作しないようです。
>
> `from_email` と `return_path` 1つのメールアドレスを設定した場合は正しく複数の送信先に送信できました。

上記のようにコメントいただいておりますが、上記の通り、ご認識の通りです。

上記の文章は「送信先メールアドレス」についての説明文章です（下記スクリーンショット画像もご確認ください。）。

![スクリーンショット 2024-05-23 11 49 25](https://github.com/dounokouno/TransmitMail/assets/215381/2febbb63-cccd-4a65-829b-d9bee9b9653a)

`auto_reply_from_email` の説明文章やその他のメールアドレスの設定の説明文章ではないので、説明文章としては特に間違っていないように思います。

issue のタイトルが「設定ファイルの記述方法（v2）「複数の宛先に送信する場合」の説明について」とありますが、 @miralkashiwagi 様はこの説明文章について、どのような疑問点、問題点、説明不足、誤認してしまう表現などを感じていらっしゃいますでしょうか？

**Comment by miralkashiwagi** [comment]
@dounokouno ご返信ありがとうございます。

> どのような疑問点、問題点、説明不足、誤認してしまう表現などを感じていらっしゃいますでしょうか？

こちら、当方の説明に不足がありまして失礼いたしました。
テキストで上手く説明できず申し訳ないのですが、以下のような形となります。

# 経緯
スクリーンショットを貼り付けていただいた箇所につきまして、当初

`email: info@example.com,test@example.com` と設定した上で
`auto_reply_from_email: info@example.com` のように設定する必要がある

という意味だと読みました。

### Wikiから想定した設定イメージ
```
config:
    email: info@example.com,test@example.com
    subject: ［株式会社テスト］お問い合わせ
    auto_reply_subject: ［株式会社テスト］お問い合わせありがとうございます
    auto_reply_name: 株式会社テスト
    auto_reply_from_email: info@example.com
    return_path: info@example.com
```



しかし、上記のように設定した場合には、`email` に指定したメールアドレスのうち片方（2つ設定したとき、左側の方）にしかメールが届かず、
複数の宛先にはメールが届きませんでした。

そこで TransmitMail.php を読みましたところ `from_email` という設定がありましたので
`from_email` を設定するようにしてみましたところ、複数の宛先にメールが届きました。

### 動作したときの設定イメージ
```
config:
    email: info@example.com,test@example.com
    subject: ［株式会社テスト］お問い合わせ
    auto_reply_subject: ［株式会社テスト］お問い合わせありがとうございます
    auto_reply_name: 株式会社テスト
    auto_reply_from_email: info@example.com
    from_email: info@example.com
    return_path: info@example.com
```

# 分かりにくかったと考えられる点
- 複数の宛先に送信する場合の説明からは `auto_reply_from_email` を設定するように読め、
 実際には `from_email` の指定が必要だということが読み取れませんでした。
- Wiki内には `from_email` について述べている箇所がなく、
TransmitMail.phpを読まない限り `auto_reply_from_email`とは別途
 `from_email` の設定が存在することが読み取れませんでした。
